title: 枫之楚
description: 

url: https://fengzhichu.github.io
baseurl:
enforce_ssl: fengzhichu.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 6

navigation:
 - title: 主页 | HOME
   url: /index.html
 - title: 类目 | CATEGORY
   url: /categories.html
 - title: 标签 | TAGS
   url: /tags.html
 - title: 关于 | ABOUT
   url: /about.html
 - title: 联系 | CONTACT
   url: /contact.html

social:
   github: fengzhichu
   twitter: fengzhichu
   facebook: 
   email: contact@fengzhichu.com

google_analytics: "UA-69523445-1"
