# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fengzhichu.com" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"
# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "枫之楚"
  #avatar: avatar.png
  hometitle: "首页"
  yoursitetitle: FENGZHICHU
  gravatar: # Email MD5 hash
  description: "一位Swifter的独白！" # used by search engines
  visiblewords: 500
  # Header and footer text
  header_text: >
     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  #   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="https://fengzhichu.com">枫之楚</a> 

  # Icons
  rss: false
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "fengzhichu"
  weibo: "fengzhichu"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: "amazation"
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "fengzhichu"
  wordpress:
  youtube:
  email_address: "contact@fengzhichu.com" # Full email address, e.g. "sam@example.com"

  # Scripts
  google_analytics: "UA-69523445-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "fengzhichu"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "关注我的" #"Follow on"
  str_rss_follow: "订阅 RSS" #"Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "更多..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: "fengzhichu.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

# ARCHIVES
gems:
  - jekyll-archives

jekyll-archives:
  enabled:
    - month
  layout: "archive"
  permalinks:
    month: "/archives/month/:year-:month/"