title: 枫之楚
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://fengzhichu.github.io
baseurl:
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 6

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about.html
 - title: 联系
   url: /contact.html

social:
   github: fengzhichu
   twitter: fengzhichu
   facebook: fengzhichu
   email: fengzhichu@live.com

google_analytics: "UA-58263416-1"
